// Auto-generated by Supabase CLI — do not edit manually
// This is a placeholder. Run `pnpm supabase gen types` after DB is set up.
// biome-ignore lint/suspicious/noExplicitAny: placeholder until generated types exist
export type Database = any
