// Auto-generated by Supabase CLI — do not edit manually
// This is a placeholder. Run `pnpm supabase gen types` after DB is set up.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type Database = any
